apiVersion: v1
kind: Pod 
metadata:
  name: myfirstpod
  labels:
    app: myflaskapp
    
spec:
  containers:
    - name: myfirstpod
      image: psrv3/cicdbatch12
      ports:
        - containerPort: 5001