apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-08-26T08:48:12Z"
  labels:
    run: myflaskpod
  name: myflaskpod
  namespace: default
  resourceVersion: "3463"
  uid: aed0976f-e972-434a-96f7-8b109570f53f
spec:
  containers:
  - image: psrv3/cicdbatch12
    imagePullPolicy: Always
    name: myflaskpod
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-hjsgg
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-hjsgg
    secret:
      defaultMode: 420
      secretName: default-token-hjsgg
status:
  phase: Pending
  qosClass: BestEffort
